apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users.fullname" . }}-deploy
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "users.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "users.fullname" . }}
      annotations:                              
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: /prometheus
    spec:
      containers:
        - name: spring-app
          image: {{ .Values.deployment.appImage.repository }}:{{ .Chart.AppVersion }}
          envFrom:
            - configMapRef:
                name: {{ include "users.fullname" . }}-configmap
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "users.fullname" . }}-secret
                  key: postgres-password
          ports:
            - containerPort: {{ .Values.deployment.appPort }}
