apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "users.fullname" . }}-configmap
data:
  DB_USERNAME: postgres
  DB_URL: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/
  BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9091