apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse.fullname" . }}
  labels: 
    app: {{ include "warehouse.fullname" . }}
spec:
  selector: 
    app: {{ include "warehouse.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.deployment.appPort }}
      name: web
    
