spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: "classpath:db.changelog/update.xml"
    enabled: true
    drop-first: false
    default-schema: ORDERS
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ORDERS

outbound:
  authProviderUrl: ${AUTH_SERVER_URL}/users/auth
redis:
  host: ${REDIS_HOSTNAME:127.0.0.1}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD}

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}


