fullnameOverride: orders

deployment:
  replicas: 3
  appImage: 
    repository: vikonopleva/orders
  appPort: 8001

service:
  appPort: 8001
  serviceType: ClusterIP

gateway:
  prefix: /otusapp/victoria/

postgresql:
  enabled: true
  auth:
    postgresPassword: vika
  initdbScripts:
    init-users-schema.sql: |
      CREATE SCHEMA IF NOT EXISTS ORDERS;

metrics:
  serviceMonitor:
    enabled: true
