spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: "classpath:db.changelog/update.xml"
    enabled: true
    drop-first: false
    default-schema: BILLING
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: BILLING

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}

outbound:
  authProviderUrl: ${AUTH_SERVER_URL}/users/auth


