fullnameOverride: crude-app

deployment:
  replicas: 3
  appImage: 
    repository: vikonopleva/crudeapp
    tag: 1.7
  appPort: 8000

service:
  appPort: 8000
  serviceType: ClusterIP

ingress:
  hostname: arch.homework

postgresql:
  enabled: true
  auth:
    postgresPassword: vika
