fullnameOverride: billing

deployment:
  replicas: 2
  appImage: 
    repository: vikonopleva/billing
  appPort: 8002

service:
  appPort: 8002
  serviceType: ClusterIP

gateway:
  prefix: /otusapp/victoria/

metrics:
  serviceMonitor:
    enabled: true
