apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "crudeapp.fullname" . }}-gateway
spec:
  # The selector matches the ingress gateway pod labels.
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "crudeapp.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "crudeapp.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.gateway.prefix }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "crudeapp.fullname" . }}
        port:
          number: {{ .Values.service.appPort }}