fullnameOverride: warehouse

deployment:
  replicas: 3
  appImage: 
    repository: vikonopleva/warehouse
  appPort: 8004

service:
  appPort: 8004
  serviceType: ClusterIP

gateway:
  prefix: /otusapp/victoria/

postgresql:
  enabled: true
  auth:
    postgresPassword: vika
  initdbScripts:
    init-users-schema.sql: |
      CREATE SCHEMA IF NOT EXISTS WAREHOUSE;

metrics:
  serviceMonitor:
    enabled: true
