fullnameOverride: delivery

deployment:
  replicas: 3
  appImage: 
    repository: vikonopleva/delivery
  appPort: 8003

service:
  appPort: 8003
  serviceType: ClusterIP

gateway:
  prefix: /otusapp/victoria/

postgresql:
  enabled: true
  auth:
    postgresPassword: vika
  initdbScripts:
    init-users-schema.sql: |
      CREATE SCHEMA IF NOT EXISTS DELIVERY;

metrics:
  serviceMonitor:
    enabled: true
