server:
    servlet.context-path: /
    port: 8004

spring:
  datasource:
      url: jdbc:h2:mem:default
      username: Victoria
      password:
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: "classpath:db.changelog/update.xml"
    enabled: true
    drop-first: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

kafka:
  consumer:
    group-id: local-warehouse
    properties:
      spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.json.value.default.type: java.lang.String
      spring.deserializer.key.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  topics:
    order-payment-accepted: ORDER_PAYMENT
    order-delivery-cancel: DELIVERY_CANCEL
    item-reserve-cancelled: RESERVE_CANCEL
  bootstrap-servers: 127.0.0.1:9092

management.endpoints.web.exposure.include: health, prometheus
management.endpoint.prometheus.enabled: true
management.endpoints.web.base-path: /
management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true










