server:
    servlet.context-path: /
    port: 8001

spring:
  datasource:
      url: jdbc:h2:mem:default
      username: Victoria
      password:
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: "classpath:db.changelog/update.xml"
    enabled: true
    drop-first: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

outbound:
  authProviderUrl: http://localhost:8000/users/auth

management.endpoints.web.exposure.include: health, prometheus
management.endpoint.prometheus.enabled: true
management.endpoints.web.base-path: /
management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true










