apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.fullname" . }}-configmap
data:
  DB_USERNAME: postgres
  DB_URL: jdbc:postgresql://users-chart-postgresql:5432/
  AUTH_SERVER_URL: http://users.default.svc.cluster.local:8000
  REDIS_HOSTNAME: redis-service-master.default.svc.cluster.local
  REDIS_PASSWORD: VgUQ9mjbH3
  BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092